### imports

In [7]:
import numpy as np
from sklearn.datasets import fetch_california_housing
from my_ml.datasets import load_spambase

KeyboardInterrupt: 

In [ ]:
from my_ml.linear_models.regression import LinearRegression
from my_ml.preprocessing import Data_split,KFold

In [ ]:
from my_ml.trees import DecisionTree_Classification, DecisionTree_Regression,RandomForestClassification

In [ ]:
import numpy as np

def confusion_matrix(y_true, y_pred):
    classes = np.unique(np.concatenate((y_true, y_pred)))
    n = len(classes)
    cm = np.zeros((n, n), dtype=int)

    class_to_idx = {cls: i for i, cls in enumerate(classes)}

    for t, p in zip(y_true, y_pred):
        cm[class_to_idx[t], class_to_idx[p]] += 1

    return cm


### Decision Trees

In [ ]:
X,y = load_spambase()

In [ ]:
(X_train,y_train),(X_test,y_test),(X_val,y_val) = Data_split(X,y,[0.5,0.25],True,True)

In [ ]:
fold = KFold(k_split=5,shuffle=True)
splits = list(fold.split(X))

In [ ]:
X, y = fetch_california_housing(return_X_y=True)

In [ ]:
model = DecisionTree_Regression(
   threshold=0.01,
   max_depth=5,
   min_samples_split=80,
   min_samples_leaf=40,
)


In [ ]:
model.fit(X,y)

In [ ]:
y_pred = model.predict(X)

### PCA test

In [ ]:
from my_ml.decomposition import PCA,KPCA

In [ ]:
X,y = load_spambase()

In [ ]:
decomp = KPCA(n_components=2,gamma=1.0)
decomp.fit(X)

In [ ]:
X_trans = decomp.transform(X)

In [ ]:
X_trans

array([[4.97802848e-06, 4.97938295e-06],
       [3.24702633e-06, 3.22263730e-06],
       [3.24626258e-06, 3.22186819e-06],
       ...,
       [3.24894779e-06, 3.22457240e-06],
       [3.50018160e-06, 3.47790223e-06],
       [3.24672763e-06, 3.22233660e-06]], shape=(4601, 2))

### tensor

In [1]:
import numpy as np
import my_ml
from my_ml.mytorch import tensor

In [2]:
a = tensor(np.array([1,2]))

In [3]:
b = tensor([[1],[2]])

In [4]:
c= a+b

In [5]:
c.grad

array([[0., 0.],
       [0., 0.]])

In [6]:
c.grad = np.array([[1.,1.],[1.,1.]])

In [7]:
c.grad

array([[1., 1.],
       [1., 1.]])

In [8]:
c._backward()

In [9]:
a.grad

array([2., 2.])

In [10]:
a

tensor(
  data=
    [1 2],
  grad=
    [2. 2.]
)

In [11]:
c

tensor(
  data=
    [[2. 3.]
     [3. 4.]],
  grad=
    [[1. 1.]
     [1. 1.]]
)

In [12]:
b

tensor(
  data=
    [[1.]
     [2.]],
  grad=
    [[2.]
     [2.]]
)

In [13]:
a

tensor(
  data=
    [1 2],
  grad=
    [2. 2.]
)